//! Render the tool catalog as a Markdown reference, generated from the same input
//! schemas that clients receive.
use std::fmt::Write as _;

use rmcp::model::Tool;
use serde_json::{Map, Value};

/// A Markdown reference of every tool, its actions, and their fields.
#[must_use]
pub fn markdown(tools: &[Tool]) -> String {
    let mut out = String::from(
        "# Tool reference\n\n<!-- Generated by `word-mcp --tools-markdown`; do not edit by hand. -->\n\n\
         Every tool takes `path` and an `operation` object whose `action` selects what to do; \
         the remaining `operation` fields depend on the action.\n\n",
    );
    for tool in tools {
        let _ = writeln!(out, "- [`{}`](#{})", tool.name, tool.name);
    }
    out.push('\n');
    for tool in tools {
        render_tool(&mut out, tool);
    }
    out
}

fn render_tool(out: &mut String, tool: &Tool) {
    let schema = Value::Object(tool.input_schema.as_ref().clone());
    let defs = schema
        .get("$defs")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let _ = writeln!(out, "## `{}`\n", tool.name);
    if let Some(description) = &tool.description {
        let _ = writeln!(out, "{description}\n");
    }
    if let Some(annotations) = &tool.annotations {
        let effect = if annotations.read_only_hint == Some(true) {
            "read-only"
        } else if annotations.destructive_hint == Some(true) {
            "may modify documents"
        } else {
            "additive"
        };
        let _ = writeln!(out, "*Effect: {effect}.*\n");
    }
    let properties = schema.get("properties").and_then(Value::as_object);
    let required = required(&schema);
    if let Some(path) = properties.and_then(|properties| properties.get("path")) {
        let necessity = if required.contains(&"path") {
            "required"
        } else {
            "optional"
        };
        let _ = writeln!(
            out,
            "`path` ({necessity}): {}\n",
            description(path).unwrap_or_default()
        );
    }
    let Some(operation) = properties.and_then(|properties| properties.get("operation")) else {
        return;
    };
    let variants = resolve(operation, &defs)
        .get("oneOf")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    if variants.is_empty() {
        out.push_str("No actions.\n\n");
        return;
    }
    let _ = writeln!(out, "| Action | Description |\n| --- | --- |");
    for variant in &variants {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            action_name(variant),
            cell(description(variant).unwrap_or_default())
        );
    }
    out.push('\n');
    for variant in &variants {
        render_action(out, variant, &defs);
    }
}

fn render_action(out: &mut String, variant: &Value, defs: &Map<String, Value>) {
    let _ = writeln!(out, "### `{}`\n", action_name(variant));
    if let Some(description) = description(variant) {
        let _ = writeln!(out, "{description}\n");
    }
    let Some(properties) = variant.get("properties").and_then(Value::as_object) else {
        return;
    };
    let required = required(variant);
    let fields: Vec<_> = properties
        .iter()
        .filter(|(name, _)| name.as_str() != "action")
        .collect();
    if fields.is_empty() {
        out.push_str("No fields.\n\n");
        return;
    }
    out.push_str("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n");
    for (name, field) in fields {
        let _ = writeln!(
            out,
            "| `{name}` | {} | {} | {} |",
            cell(&type_name(field, defs)),
            if required.contains(&name.as_str()) {
                "yes"
            } else {
                "no"
            },
            cell(&details(field))
        );
    }
    out.push('\n');
}

fn action_name(variant: &Value) -> &str {
    variant
        .pointer("/properties/action/const")
        .and_then(Value::as_str)
        .unwrap_or("?")
}

fn required(schema: &Value) -> Vec<&str> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .map(|names| names.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default()
}

fn description(schema: &Value) -> Option<&str> {
    schema.get("description").and_then(Value::as_str)
}

/// Follow a local `$ref` into `$defs`.
fn resolve<'a>(schema: &'a Value, defs: &'a Map<String, Value>) -> &'a Value {
    schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|reference| reference.strip_prefix("#/$defs/"))
        .and_then(|name| defs.get(name))
        .unwrap_or(schema)
}

/// A compact human-readable type, without `null`.
fn type_name(schema: &Value, defs: &Map<String, Value>) -> String {
    let schema = resolve(schema, defs);
    if let Some(values) = enum_values(schema) {
        return values
            .iter()
            .map(|value| format!("`{value}`"))
            .collect::<Vec<_>>()
            .join(" \\| ");
    }
    if let Some(options) = schema.get("anyOf").and_then(Value::as_array) {
        return options
            .iter()
            .filter(|option| option.get("type") != Some(&Value::from("null")))
            .map(|option| type_name(option, defs))
            .collect::<Vec<_>>()
            .join(" or ");
    }
    let kind = match schema.get("type") {
        Some(Value::String(kind)) => kind.clone(),
        Some(Value::Array(kinds)) => kinds
            .iter()
            .filter_map(Value::as_str)
            .filter(|kind| *kind != "null")
            .collect::<Vec<_>>()
            .join(" or "),
        _ => "object".to_owned(),
    };
    if kind == "array" {
        let item = schema
            .get("items")
            .map_or_else(|| "value".to_owned(), |item| type_name(item, defs));
        return format!("array of {item}");
    }
    kind
}

/// The string values of an enum, written either as `enum` or as `oneOf` constants.
fn enum_values(schema: &Value) -> Option<Vec<String>> {
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return Some(
            values
                .iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect(),
        );
    }
    let options = schema.get("oneOf")?.as_array()?;
    options
        .iter()
        .map(|option| {
            option
                .get("const")
                .or_else(|| option.pointer("/enum/0"))
                .and_then(Value::as_str)
                .map(ToOwned::to_owned)
        })
        .collect()
}

/// Description plus constraints and default.
fn details(schema: &Value) -> String {
    let mut text = description(schema).unwrap_or_default().to_owned();
    let mut facts = Vec::new();
    for (keyword, label) in [
        ("minimum", "min"),
        ("maximum", "max"),
        ("minLength", "min length"),
        ("minItems", "min items"),
    ] {
        if let Some(value) = schema.get(keyword) {
            // Unsigned integers always carry `minimum: 0`; it says nothing new.
            if keyword == "minimum" && value.as_f64() == Some(0.0) && schema.get("format").is_some()
            {
                continue;
            }
            facts.push(format!("{label} {value}"));
        }
    }
    if let Some(default) = schema.get("default") {
        facts.push(format!("default `{default}`"));
    }
    if !facts.is_empty() {
        if !text.is_empty() {
            text.push(' ');
        }
        let _ = write!(text, "({})", facts.join(", "));
    }
    text
}

/// Make text safe inside a Markdown table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}
